### GET request to api health endpoint
GET {{BASE_URL}}/health

### POST request to api /sign-up endpoint
POST {{BASE_URL}}/auth/sign-up
Content-Type: application/json

{
  "firstName": "{{$random.name.firstName}}",
  "lastName": "{{$random.name.lastName}}",
  "email": "{{$random.internet.emailAddress}}",
  "password": "{{$random.internet.password}}"
}

### POST request to api /sign-up endpoint
POST {{BASE_URL}}/auth/sign-in
Content-Type: application/json

{
  "email": "{{user-1.USER_EMAIL}}",
  "password": "{{user-1.USER_PWD}}"
}

> {% client.global.set("auth_token", response.body["token"]); %}

### POST request to /sign-out endpoint
POST {{BASE_URL}}/auth/sign-out
Authorization: Bearer {{auth_token}}