services:
  auth-db:
    image: postgres:17.2-alpine
    container_name: auth_db
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./src/lib/db/db-volume:/var/lib/postgresql/data